/**
 * Sample templates and default data structures
 */

const sampleTemplate = {
  panelData: {
    type: "panel",
    name: "MyAddon",
    displayName: "My Addon Settings",
    author: "AuthorName",
    version: "1.0",
    slashCommand: "/myaddon",
    registerForRefresh: true,
    registerForDefaults: true,
  },
  optionsTable: [
    {
      type: "header",
      name: "My First Header",
      width: "full",
    },
    {
      type: "description",
      text: "This is my first section containing only full widths.",
      width: "full",
    },
    {
      type: "checkbox",
      name: "My Checkbox",
      tooltip: "Checkbox's tooltip text.",
      getFunc: { __luaFn: true, code: "function() return true end" },
      setFunc: { __luaFn: true, code: "function(value) d(value) end" },
      width: "full",
      default: "sv.enableSetting",
    },
    {
      type: "dropdown",
      name: "My Dropdown",
      tooltip: "Dropdown's tooltip text.",
      choices: ["Option 1", "Option 2", "Option 3"],
      getFunc: { __luaFn: true, code: "function() return \"of\" end" },
      setFunc: { __luaFn: true, code: "function(var) print(var) end" },
      width: "full",
      default: "sv.selectedOption",
    },
    {
      type: "slider",
      name: "My Slider",
      tooltip: "Slider's tooltip text.",
      min: 0,
      max: 20,
      step: 1,
      getFunc: { __luaFn: true, code: "function() return 3 end" },
      setFunc: { __luaFn: true, code: "function(value) d(value) end" },
      width: "full",
      default: "sv.sliderValue",
    },
    {
      type: "colorpicker",
      name: "My Color Picker",
      tooltip: "Color Picker's tooltip text.",
      getFunc: { __luaFn: true, code: "function() return 1, 0, 0, 1 end" },
      setFunc: { __luaFn: true, code: "function(r,g,b,a) print(r, g, b, a) end" },
      width: "full",
      default: "sv.colorSetting",
    },
    {
      type: "button",
      name: "My Button",
      tooltip: "Button's tooltip text.",
      func: { __luaFn: true, code: "function() d(\"button pressed!\") end" },
      width: "full",
    },
    {
      type: "header",
      name: "My Second Header",
      width: "full",
    },
    {
      type: "description",
      text: "This is my second section containing only half widths.",
      width: "full",
    },
    {
      type: "checkbox",
      name: "My Checkbox",
      tooltip: "Checkbox's tooltip text.",
      getFunc: { __luaFn: true, code: "function() return true end" },
      setFunc: { __luaFn: true, code: "function(value) d(value) end" },
      width: "half",
      default: "true",
    },
    {
      type: "dropdown",
      name: "My Dropdown",
      tooltip: "Dropdown's tooltip text.",
      choices: ["Option 4", "Option 5", "Option 6"],
      getFunc: { __luaFn: true, code: "function() return \"of\" end" },
      setFunc: { __luaFn: true, code: "function(var) print(var) end" },
      width: "half",
      default: '"Option 5"',
    },
    {
      type: "slider",
      name: "My Slider",
      tooltip: "Slider's tooltip text.",
      min: 0,
      max: 20,
      step: 1,
      getFunc: { __luaFn: true, code: "function() return 3 end" },
      setFunc: { __luaFn: true, code: "function(value) d(value) end" },
      width: "half",
      default: "10",
    },
    {
      type: "colorpicker",
      name: "My Color Picker",
      tooltip: "Color Picker's tooltip text.",
      getFunc: { __luaFn: true, code: "function() return 1, 0, 0, 1 end" },
      setFunc: { __luaFn: true, code: "function(r,g,b,a) print(r, g, b, a) end" },
      width: "half",
      default: "{r=1,g=0,b=0,a=1}",
    },
    {
      type: "button",
      name: "My Button",
      tooltip: "Button's tooltip text.",
      func: { __luaFn: true, code: "function() d(\"button pressed!\") end" },
      width: "half",
    },
  ],
};